const api=require('../../utils/api');const c=require('../../utils/cart')
Page({
 data:{location:{},detail:'',phone:'',remark:'',deliveryFee:'--',distance:'',distanceSource:'',total:'0.00',requestKey:'',quoteReady:false,quoteError:'',submitting:false},
 onLoad(){this.setData({requestKey:`order-${Date.now()}-${Math.random().toString(36).slice(2,10)}`})},
 onShow(){this.refreshTotal()}, refreshTotal(){this.setData({total:(c.total()+2).toFixed(2)})},
 inputDetail(e){this.setData({detail:e.detail.value})},inputPhone(e){this.setData({phone:e.detail.value})},inputRemark(e){this.setData({remark:e.detail.value})},
 setLocation(location){this.setData({location,quoteReady:false,quoteError:'',distance:'',distanceSource:'',deliveryFee:'--',total:c.total().toFixed(2)});api.request(`/delivery/quote?latitude=${location.latitude}&longitude=${location.longitude}`).then(q=>this.setData({distance:q.distance_km,distanceSource:q.distance_source,deliveryFee:Number(q.delivery_fee).toFixed(2),total:(c.total()+Number(q.delivery_fee)).toFixed(2),quoteReady:true})).catch(e=>this.setData({quoteError:e.detail||'暂时无法计算配送费，请稍后重试'}))},
 chooseLocation(){wx.chooseLocation({success:r=>this.setLocation({name:r.name||r.address,latitude:r.latitude,longitude:r.longitude}),fail:()=>wx.showToast({title:'未选择地图地点',icon:'none'})})},
 useCurrentLocation(){wx.getLocation({type:'gcj02',success:r=>this.setLocation({name:'当前位置',latitude:r.latitude,longitude:r.longitude}),fail:()=>wx.showToast({title:'请授权定位',icon:'none'})})},
 submit(){const {location,detail,phone,remark,requestKey,quoteReady,submitting}=this.data;if(submitting)return;if(!location.latitude||!detail||!phone)return wx.showToast({title:'请完整填写收货信息',icon:'none'});if(!quoteReady)return wx.showToast({title:'请先等待配送费计算完成',icon:'none'});this.setData({submitting:true});const items=c.getCart().map(x=>({product_id:x.id,quantity:x.quantity}));api.request('/orders','POST',{items,address:{name:location.name,detail,latitude:location.latitude,longitude:location.longitude,phone},remark},{'X-Idempotency-Key':requestKey}).then(order=>api.request(`/orders/${order.id}/mock-payment-callback`,'POST').then(paid=>{c.saveCart([]);wx.redirectTo({url:`/pages/order-result/index?id=${paid.id}&no=${paid.order_no}`})})).catch(e=>{this.setData({submitting:false});wx.showToast({title:e.detail||'下单失败',icon:'none'})})}
})
